name: Lint and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install openai python-dotenv
      - name: Lint Python files
        run: |
          pip install flake8
          flake8 .
      - name: Run LLM Tool Example
        run: |
          python llm_tool_example.py || true
